public enum AdvancementState {
    NEW_GAME = 0,
    GET_BANANAGUN = 1,
    GRAB_DEBRIS_ON_MAP = 2,
    FIRST_PLATFORM_BUILD = 3,
    OPEN_INVENTORY = 4,
    EQUIP_PLATFORM = 5,
    PUT_PLATFORM = 6,
    PUT_BANANA_ON_PLATFORM = 7,
    GRAB_BANANAS = 8,
    FEED_GORILLA = 9
}