public enum BananaType {
    BARANGAN,
    BLUE_JAVA,
    BURRO,
    CAVENDISH,
    GOLD_FINGER,
    GROS_MICHEL,
    LADY_FINGER,
    MATOKE,
    MUSA_VELUTINA,
    NANJANGUD,
    PISANG_RAJA,
    PLANTAIN,
    PRAYING_HANDS,
    RED,
    RINO_HORN,
    TINDOK
}