public enum BuildableType {
    BUMPER,
    BANANA_DRYER,
    GUICHET,
    RETRIEVER,
    PORTAL, // TO RECYCLE
    ARCADE_MACHINE_LITTLE_01,
    BENCH_LITTLE_01,
    BENCH_LITTLE_02,
    BENCH_LITTLE_03,
    BENCH_LITTLE_04,
    ROUNDED_KNOWLEDGE_BOARD_LITTLE_01,
    SQUARED_KNOWLEDGE_BOARD_LITTLE_01,
    THICK_KNOWLEDGE_BOARD_LITTLE_01,
    DISTRIBUTOR_LITTLE_01,
    DISTRIBUTOR_LITTLE_02,
    DISTRIBUTOR_LITTLE_03,
    CHAIR_LITTLE_01,
    BLUEPRINTS_WORKSTATION
}