public enum GameContext {
    NEW_GAME,
    IN_GAME,
    IN_CINEMATIQUE,
    IN_HOME,
    IN_GESTION_VIEW,
    IN_GAME_MENU,
    DEAD,
    IN_BANANA_SELECTOR,
    IN_COMMAND_ROOM_PANEL,
    IN_GESTION_PANEL
}
