public enum GameContext {
    IN_GAME,
    IN_CINEMATIQUE,
    IN_HOME,
    IN_GESTION_VIEW,
    IN_BANANA_CANNON_MINI_GAME,
    IN_MARKETING_MINI_GAME,
    IN_VISITOR_WAITING_LIST_MINI_GAME,
    IN_INVENTORY,
    IN_GAME_MENU,
    DEAD
}