public enum InputContext {
    GAME,
    UI,
    GESTION,
    SPACE_TRAFFIC_CONTROL_MINI_GAME,
    INVENTORY,
    HOME,
    GESTION_COMMAND_ROOM_PANEL,
    VISITOR_WAITING_LIST_MINI_GAME,
    MERCHANT
}