public enum InputContext {
    GAME,
    UI,
    GESTION,
    SPACE_TRAFFIC_CONTROL_MINI_GAME,
    INVENTORY,
    HOME,
    VISITOR_WAITING_LIST_MINI_GAME,
    MERCHANT,
    MAP,
    BANANA_SELECTOR
}