public enum InteractionType {
    BUBBLE,
    BANANAGUN,
    GRABBABLE_PIECE,
    DISTRIBUTOR,
    MANAGEMENT_WORKSTATION,
    RETRIEVER,
    TELEPORT,
    MESSAGE,
    BANANA_DRYER,
    MARKETING_COMMAND_ROOM_PANEL,
    GESTION_COMMAND_ROOM_PANEL,
    SPACE_TRAFFIC_COMMAND_ROOM_PANEL,
    JOURNAL_COMMAND_ROOM_PANEL,
    GUICHET,
    MERCHANT
}