public enum ItemStaticType {
    DOOR_BEETWEEN_LEVELS,
    MINI_CHIMP,
    BANANAGUN,
    COMMAND_ROOM_PANEL,
    BANANA_DRYER,
    BANANA_CANNON_MINI_GAME,
    DOOR_LEFT,
    DOOR_RIGHT,
    GRABBABLE_PIECE
}