public enum ItemStaticType {
    DOOR_BEETWEEN_LEVELS,
    BUBBLE,
    BANANAGUN,
    COMMAND_ROOM_PANEL,
    BANANA_DRYER_PLACE_BANANA_PEEL,
    BANANA_CANNON_MINI_GAME,
    GRABBABLE_PIECE,
    RETRIEVER,
    BLUEPRINTS_DATA,
    TELEPORT_TO_PORTAL_DESTINATION,
    BANANA_DRYER_TAKE_FABRIC
}