public enum ItemStaticType {
    DOOR_BEETWEEN_LEVELS,
    MINI_CHIMP_COMMAND_ROOM,
    BANANAGUN,
    COMMAND_ROOM_PANEL,
    BANANA_DRYER,
    BANANA_CANNON_MINI_GAME,
    GRABBABLE_PIECE,
    RETRIEVER,
    BLUEPRINTS_DATA,
    PORTAL_DESTINATION
}