public enum SoundEffectType {
    BANANASPLASH,
    BUTTON_INTERACTION,
    DESINTEGRATION,
    THROW_BANANA,
    TAKE_SOMETHING,
    OPEN_DOOR,
    EAT_BANANA,
    GUITAR_RYTHM_01,
    GRAB_SOMETHING,
    NO_BANANA,
    CANNON_SHOOT,
    LAUNCH_SIGNAL,
    COUNTDOWN
}