namespace Enums {
    public enum SpawnPoint {
        HOME,
        COROLLE_TO_MAP01,
        MAP01_TO_COROLLE,
        COMMAND_ROOM_TO_COROLLE_DOOR1,
        COMMAND_ROOM_TO_COROLLE_DOOR2,
        COROLLE_TO_COMMAND_ROOM_DOOR1,
        COROLLE_TO_COMMAND_ROOM_DOOR2,
        COMMAND_ROOM_TELEPORTATION,
        LAST_MAP
    }
}
