public enum TouristState {
    GO_TO_TELEPORTER,
    SEARCH_WAITING_LINE,
    GO_TO_WAITING_LINE,
    IN_WAITING_LINE,
    SEARCH_NEED,
    GO_FILL_NEED,
    FILLING_NEED,
    SEARCH_RANDOM_POINT,
    GO_TO_RANDOM_POINT,
    GO_BACK_TO_TELEPORTER,
    GO_BACK_TO_SPACESHIP
}
