public enum TouristState {
    GO_TO_COROLLE_CENTER,
    SEARCH_WAITING_LINE,
    GO_TO_WAITING_LINE,
    IN_WAITING_LINE,
    SEARCH_NEED,
    GO_FILL_NEED,
    FILLING_NEED,
    SEARCH_MAP_TO_VISIT,
    GO_TO_ENDMAP,
    GO_BACK_TO_SPACESHIP
}
