public enum TravelState {
    FREE_FLIGHT,
    GO_TO_PATH,
    TRAVEL_ON_PATH,
    TRAVEL_ON_ELEVATOR,
    WAIT_IN_STATION,
    TRAVEL_BACK_ON_ELEVATOR,
    TRAVEL_BACK_ON_PATH,
    LEAVES_THE_REGION
}
