public enum UICanvasGroupType {
    HOME_MENU,
    GAME_MENU,
    LOAD,
    OPTIONS,
    BANANAPEDIA,
    CREDITS,
    DEATH,
    HUD,
    INVENTORY,
    BLUEPRINTS,
    STATISTICS,
    TUTORIALS,
    MINIGAME,
    BUILD_HELPER,
    BUILD_HELPER_Y_AXIS,
    BUILD_HELPER_Z_AXIS
}